apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: docker.io/waveywaves/mirrord-nodejs-example:v3
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_URL
          value: redis://redis
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-guestbook
spec:
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer